pointcloud_saver_node:
  ros__parameters:
    save_interval: 5.0          # Time in seconds between consecutive saves
    target_frame: "base_link"   # Frame to transform the point cloud to
    save_retries: 5             # Number of retries for saving the file