#manipulator:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
manipulator:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  max_cache_size: 10000
  min_pose_distance: 1.0
  min_joint_config_distance: 4.0
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

#gripper:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005

#gripper:
#  kinematics_solver: robot_state/RobotStatePlugin
