# Empty sensors configuration to avoid parameter normalization issues
# The occupancy map monitor can be configured separately if needed
sensors: []

# sensors:
#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /camera/depth/color/points
#     max_range: 5.0
#     point_subsample: 1
#     padding_offset: 0.1
#     padding_scale: 1.0
#     max_update_rate: 1.0
#     filtered_cloud_topic: filtered_cloud
