# Request
# task name
string task_name
# what kind of movement we want
# with respect to end_effector
string END_EFFECTOR_LINK = "end_effector_link"
# with respect to base_link
string BASE_LINK = "base_link"
# with respect to camera_link
string CAMERA_DEPTH_FRAME = "camera_depth_frame"
string movement_link
# 3D position relative to the link you choose
geometry_msgs/Pose pose

---
# Result
# Position is reachable or not
string result

---
# Feedback
string processing_status
